services:
  db:
    image: postgres:15
    container_name: bliss_db
    env_file: 
      - .env_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - blissnet
    
    
  web: 
    build: .
    container_name: bliss_web
    volumes: 
      - .:/app
    depends_on:
      - db
    env_file:
      - .env_web
    volumes:
      - ./static:/app/static    # matches STATIC_ROOT
      - ./media:/app/media      # matches MEDIA_ROOT
    networks:
      - blissnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - blissnet


volumes: 
  db_data:

networks:
  blissnet:
    driver: bridge
    



