# Generated by Django 5.0.6 on 2024-08-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_user_id_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
    ]
